### ISSUE TITLE
Bug: module shows only "0" 

### ISSUE THREAD

**Issue by Christian420-bit** [mlbonniec/MMM-Coinbase#10]
Hey guys, 
I have installed the module. After starting magicmirror there will be only shown "0" and not the amount of my coins and the ohter stuff... 
Any ideas ?

**Comment by MagicOrhan** [comment]
Same problem for me. Followed the installation-steps and entered api key and secret key(copy/paste). The module only appears as "coinbase0"
Thanks for any advise!

**Comment by mlbonniec** [comment]
Hey!

When creating the API accesses, did you check the right wallets?

**Comment by Christian420-bit** [comment]
The first time I have done it like in the screencast: wallet:accounts:read and BTC Wallet.
This wasnt working. 
The second time I have activated all with the permission of read but it doesnt work,too.

**Comment by MagicOrhan** [comment]
I took ETH and BTC wallet and gave wallet:accounts:read permission. As additional information: In the below section is an info that I use API-Version: 2020-04-26

**Comment by Christian420-bit** [comment]
Okay I tested it with ETH and BTC wallet and wallet:accounts:read permission.
-> Same issue
But my API Version is an older one:  API-Version: 2020-01-29
It is written that I would be on the newest version...

**Comment by Zeroo92** [comment]
Same issue for me. module stay at 0.

**Comment by WeeskyBDW** [comment]
Hello
coinbase module (used in MMC-coinbase) is deprecated so the code need to be update (make directly requests)

**Comment by mlbonniec** [comment]
Hey, everyone!
I'm currently fixing this bug, and improving the code.
It was my very first time with Javascript ahah
I'll tell you when I've dealt with the problem...

**Comment by mlbonniec** [comment]
It works! The Coinbase API had changed.
I also improved slightly, and made the module compatible with all Coinbase currencies.
Try it!

**Comment by Christian420-bit** [comment]
I have just updated the module. It works perfectly. Thanks man!!

**Comment by mlbonniec** [comment]
Awesome ! Good use :wink:
