### ISSUE TITLE
 Error: ETIMEDOUT

### ISSUE THREAD

**Issue by kurtern84** [mlbonniec/MMM-Coinbase#13]
[2020-11-13 11:47:12.988] [ERROR]  Whoops! There was an uncaught exception...
[2020-11-13 11:47:12.990] [ERROR]  Error: ETIMEDOUT
    at Timeout._onTimeout (/home/pi/MagicMirror/modules/MMM-Coinbase/node_modules/request/request.js:846:19)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7) {
  code: 'ETIMEDOUT',
  connect: true
}

**Comment by mlbonniec** [comment]
Hi, first of all I'm sorry I didn't answer earlier! I didn't see your message.
Can you tell me your versions of NodeJS, NPM and MagicMirror?
Also, I can advise you to do `npm update` to update the packages (and therefore maybe the request module).

**Comment by kurtern84** [comment]
No problem :)

Nodejs v10.23.0
Npm v6.14.8
Mm V2.13

Tried npm update without no luck.

**Comment by mlbonniec** [comment]
Okay, so try to update [NodeJS](https://nodejs.org/en/) to ~v14.
Not sure that this will solve the problem, but it is better to start with a solid foundation to solve the problem.

**Comment by kurtern84** [comment]
Did the update. Still the same.

**Comment by mlbonniec** [comment]
Hi, sorry for the delay, you made an `npm update` to update the packages.
However, updating NodeJS is more complicated. You are in an old version.
Can you try to update NodeJS. The `request` module may not be compatible.
I suggest you to use the `n` module tu update NodeJS. This link may help you https://phoenixnap.com/kb/update-node-js-version

**Comment by kurtern84** [comment]
Hi! I’ve fixed it.. did a complete re-install :)

**Comment by mlbonniec** [comment]
Great! *and sorry again*
