### ISSUE TITLE
XTZ dzn't work - solution

### ISSUE THREAD

**Issue by woj-Trek** [mlbonniec/MMM-Coinbase#15]
Only XTZ will not appear. Any idea?
Edit: OXT too😕

{
    module: "MMM-Coinbase",
    position: "top_center", 
    header: "Coinbase", 
        config: {
            apiKey: "MY CORRECT KEY", 
            apiSecret: "MY CORRECT API SECRET KEY",
            wallet: ["NU", "XTZ", "FIL", "COMP", "OXT",],
            icons: true,
            label: false
        }
}

<img width="339" alt="Screenshot 2020-12-16 134652" src="https://user-images.githubusercontent.com/63651060/102350446-3964e780-3fa5-11eb-8a62-54a8164e1eda.png">

**Comment by mlbonniec** [comment]
Hello ^^ I don't quite understand the problem. On the screenshot, OXT seem to appear, right?

**Comment by woj-Trek** [comment]
@mlbonniec

{
module: "MMM-Coinbase",
position: "top_center",
header: "Coinbase",
config: {
apiKey: "MY CORRECT KEY",
apiSecret: "MY CORRECT API SECRET KEY",
wallet: ["XTZ","NU",  "FIL", "OXT",],
icons: true,
label: false
}
}
![201208-MMM-Coinbase](https://user-images.githubusercontent.com/63651060/102611268-e74fcd80-412e-11eb-83ad-5b25ff6307a5.PNG)

**Comment by mlbonniec** [comment]
Hi, I personally have no worries, as the screenshot shows. Can you give me your versions, from MagicMirror, MMM-Coinbase and NodeJS. Thanks 🙂

<img width="239" alt="MMM-Coinbase works" src="https://user-images.githubusercontent.com/29955402/102766459-756dc300-437e-11eb-9bf4-18b282dc31f0.png">

Here's my `config.js`:
```js
{
	module: "MMM-Coinbase",
	position: "top_left",
	header: "Coinbase",
	config: {
		apiKey: "MY_API_KEY",
		apiSecret: "MY_API_SECRET",
		wallet: ["BTC", "LTC", "OXT", "XTZ", "NU", "FIL"],
		icons: true,
		label: false
	}
}
```

**Comment by woj-Trek** [comment]
Nodejs v10.23.0
MM 2.13.0
Mmm-Coinbase 1.0.0 (the last one?)
Raspbian 10 (buster)

**Comment by WeeskyBDW** [comment]
Try to update to NodeJS 12

**Comment by mlbonniec** [comment]
> Try to update to NodeJS 12

Yep, you're in an old version of Node. As you can see on the official website [https://nodejs.org/en/](https://nodejs.org/en/), the actual version of Node is the v14.x.x
For an update to a recent version, I suggest you to read this comment on an other issue, it may help you https://github.com/mlbonniec/MMM-Coinbase/issues/13#issuecomment-748901066

**Comment by woj-Trek** [comment]
Happy New Year!

New year old problems. I have made all new. XTZ still not appear.
Node 15
What can I do, any idea?

**Comment by woj-Trek** [comment]
And I have the solution! Look this picture below.
![API_Coinbase](https://user-images.githubusercontent.com/63651060/103750177-b0baf380-5006-11eb-882a-47dbbe5ef764.PNG)
I have had all checked.

**Comment by WeeskyBDW** [comment]
Can you explain ? Because i think no major part of people read the langage of your screen 

Thx
