### ISSUE TITLE
Portefeuille en EUR

### ISSUE THREAD

**Issue by flo57570** [mlbonniec/MMM-Coinbase#2]
Hello,

Thank you for this great module

Is it possible to display the amount of the Portfolio in EUR instead of the bitcoin amount?

**Comment by mlbonniec** [comment]
Hi!
Thank you for your feedback!
Currently the Coinbase API does not allow this. Certainly on Coinbase we see the conversion in EUR, but the API does not return this value. However, it is quite possible to use another API. I will search and keep you informed in a short time!
(I am French; but it is better to speak in English for everyone to understand)

**Comment by flo57570** [comment]
Ah, okay. Too bad.

Thank you for the quick answer.

I am also French

I look forward to your return if you find something.

**Comment by WeeskyBDW** [comment]
Hey, you can use this https://blockchain.info/ticker

**Comment by mlbonniec** [comment]
> Hey, you can use this https://blockchain.info/ticker

That's a great idea. I'll check it out! It is not complicated, a simple calculation (Value in EUR * Your Bitcoins) give your bitcoin value in EUR !

**Comment by flo57570** [comment]
Hi !!
Thk's for this, but it only works with Bitcoin

**Comment by WeeskyBDW** [comment]
What crypto monnaie do you have/do you want to convert in Euro ? I dont really understand

**Comment by flo57570** [comment]
I also have ETH and LTC in my portfolio

I found this site

https://min-api.cryptocompare.com/documentation

I would like to do (BTC*euro price)+(ETH*euro price)+(LTC*euro price)
