### ISSUE TITLE
Support for other cryptos?

### ISSUE THREAD

**Issue by nabbl** [mlbonniec/MMM-Coinbase#7]
Great module!

How about supporting more currencies on Coinbase?

**Comment by mlbonniec** [comment]
Thank you so much !

For the moment it's impossible, I will see in the future.

**Comment by nabbl** [comment]
@mlbonniec can you please add me as a maintainer as well? I implemented this myself and want to create a pull request for you to review.

**Comment by mlbonniec** [comment]
> @mlbonniec can you please add me as a maintainer as well? I implemented this myself and want to create a pull request for you to review.

To add you as maintainer I have to create a team, and I don't really want to create one just for that...
Normally you can create a pull request without being maintainer

**Comment by nabbl** [comment]
I lack permissions to push a new branch however...
https://help.github.com/en/articles/inviting-collaborators-to-a-personal-repository

**Comment by mlbonniec** [comment]
Normally it's good ;-)

**Comment by mlbonniec** [comment]
Whooo, thanks for your incredible work!
I must admit that I am no longer really motivated by this module, so your help is really valuable!
I added you to the contributors, at the bottom of the [README.md](https://github.com/mlbonniec/MMM-Coinbase/blob/master/README.md#contributors)

**Comment by nabbl** [comment]
Thx mate. I was only motivated because I have litecoins and no bitcoins. ;)

**Comment by mlbonniec** [comment]
ahaha it all makes sense 😆
